// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // ignore_for_file: type=lint,unused_import

// GENERATED BY drift_dev, DO NOT MODIFY.
final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    rides,
    sensorReadings,
    laps,
    workouts,
    workoutSteps,
    userProfiles,
    exportQueue,
  ];
  late final Shape0 rides = Shape0(
    source: i0.VersionedTable(
      entityName: 'rides',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 sensorReadings = Shape1(
    source: i0.VersionedTable(
      entityName: 'sensor_readings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 laps = Shape2(
    source: i0.VersionedTable(
      entityName: 'laps',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_19,
        _column_20,
        _column_28,
        _column_29,
        _column_1,
        _column_30,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 workouts = Shape3(
    source: i0.VersionedTable(
      entityName: 'workouts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_31, _column_32, _column_33],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 workoutSteps = Shape4(
    source: i0.VersionedTable(
      entityName: 'workout_steps',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_19,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 userProfiles = Shape5(
    source: i0.VersionedTable(
      entityName: 'user_profiles',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_31,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 exportQueue = Shape6(
    source: i0.VersionedTable(
      entityName: 'export_queue',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_19,
        _column_20,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_52,
        _column_53,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get startTime =>
      columnsByName['start_time']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get endTime =>
      columnsByName['end_time']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get workoutId =>
      columnsByName['workout_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get avgPower =>
      columnsByName['avg_power']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get normalizedPower =>
      columnsByName['normalized_power']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get maxPower =>
      columnsByName['max_power']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get avgCadence =>
      columnsByName['avg_cadence']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get avgHr =>
      columnsByName['avg_hr']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get maxHr =>
      columnsByName['max_hr']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get totalDistance =>
      columnsByName['total_distance']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get durationSeconds =>
      columnsByName['duration_seconds']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get pauseDurationSeconds =>
      columnsByName['pause_duration_seconds']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get tss =>
      columnsByName['tss']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get intensityFactor =>
      columnsByName['intensity_factor']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get ftpAtTime =>
      columnsByName['ftp_at_time']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<int> _column_1(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'start_time',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<int> _column_2(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'end_time',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'notes',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'workout_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<double> _column_7(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'avg_power',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_8(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'normalized_power',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_9(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'max_power',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_10(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'avg_cadence',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_11(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'avg_hr',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_12(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'max_hr',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_13(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'total_distance',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<int> _column_14(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'duration_seconds',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'pause_duration_seconds',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<double> _column_16(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'tss',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_17(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'intensity_factor',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_18(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'ftp_at_time',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get rideId =>
      columnsByName['ride_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get timestamp =>
      columnsByName['timestamp']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get powerWatts =>
      columnsByName['power_watts']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get cadenceRpm =>
      columnsByName['cadence_rpm']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get heartRateBpm =>
      columnsByName['heart_rate_bpm']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get speedKmh =>
      columnsByName['speed_kmh']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get distanceM =>
      columnsByName['distance_m']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get gradePercent =>
      columnsByName['grade_percent']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<int> _column_19(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'PRIMARY KEY AUTOINCREMENT',
      ),
    );
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'ride_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'REFERENCES rides (id)',
      ),
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'timestamp',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<double> _column_22(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'power_watts',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_23(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'cadence_rpm',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'heart_rate_bpm',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<double> _column_25(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'speed_kmh',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_26(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'distance_m',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_27(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'grade_percent',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get rideId =>
      columnsByName['ride_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get startIndex =>
      columnsByName['start_index']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get endIndex =>
      columnsByName['end_index']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get startTime =>
      columnsByName['start_time']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get durationMs =>
      columnsByName['duration_ms']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_28(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'start_index',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<int> _column_29(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'end_index',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<int> _column_30(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'duration_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get stepsJson =>
      columnsByName['steps_json']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'description',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'steps_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get workoutId =>
      columnsByName['workout_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get orderIndex =>
      columnsByName['order_index']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get durationSeconds =>
      columnsByName['duration_seconds']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get powerTargetPercent =>
      columnsByName['power_target_percent']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get powerLowPercent =>
      columnsByName['power_low_percent']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get powerHighPercent =>
      columnsByName['power_high_percent']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get cadenceTarget =>
      columnsByName['cadence_target']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get repeatCount =>
      columnsByName['repeat_count']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'workout_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'REFERENCES workouts (id)',
      ),
    );
i1.GeneratedColumn<int> _column_35(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'order_index',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<int> _column_37(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'duration_seconds',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<double> _column_38(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'power_target_percent',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_39(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'power_low_percent',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_40(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'power_high_percent',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<int> _column_41(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'cadence_target',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<int> _column_42(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'repeat_count',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get ftp =>
      columnsByName['ftp']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get maxHr =>
      columnsByName['max_hr']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get restHr =>
      columnsByName['rest_hr']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get weight =>
      columnsByName['weight']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get height =>
      columnsByName['height']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<double> _column_43(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'ftp',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<int> _column_44(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'max_hr',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<int> _column_45(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'rest_hr',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<double> _column_46(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'weight',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_47(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'height',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get rideId =>
      columnsByName['ride_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get target =>
      columnsByName['target']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get retryCount =>
      columnsByName['retry_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastAttempt =>
      columnsByName['last_attempt']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get errorMessage =>
      columnsByName['error_message']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_48(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'target',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_49(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      defaultValue: const CustomExpression('\'pending\''),
    );
i1.GeneratedColumn<int> _column_50(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'retry_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      defaultValue: const CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_51(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_attempt',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<String> _column_52(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'error_message',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<int> _column_53(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    rides,
    sensorReadings,
    laps,
    workouts,
    workoutSteps,
    userProfiles,
    exportQueue,
    scheduledWorkouts,
    personalRecords,
    ftpHistory,
  ];
  late final Shape0 rides = Shape0(
    source: i0.VersionedTable(
      entityName: 'rides',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 sensorReadings = Shape1(
    source: i0.VersionedTable(
      entityName: 'sensor_readings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 laps = Shape2(
    source: i0.VersionedTable(
      entityName: 'laps',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_19,
        _column_20,
        _column_28,
        _column_29,
        _column_1,
        _column_30,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 workouts = Shape3(
    source: i0.VersionedTable(
      entityName: 'workouts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_31, _column_32, _column_33],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 workoutSteps = Shape4(
    source: i0.VersionedTable(
      entityName: 'workout_steps',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_19,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 userProfiles = Shape5(
    source: i0.VersionedTable(
      entityName: 'user_profiles',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_31,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 exportQueue = Shape6(
    source: i0.VersionedTable(
      entityName: 'export_queue',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_19,
        _column_20,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_52,
        _column_53,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 scheduledWorkouts = Shape7(
    source: i0.VersionedTable(
      entityName: 'scheduled_workouts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_34,
        _column_54,
        _column_55,
        _column_4,
        _column_53,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 personalRecords = Shape8(
    source: i0.VersionedTable(
      entityName: 'personal_records',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(ride_id, duration_seconds)'],
      columns: [_column_19, _column_20, _column_37, _column_56, _column_57],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 ftpHistory = Shape9(
    source: i0.VersionedTable(
      entityName: 'ftp_history',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_19, _column_58, _column_43],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get workoutId =>
      columnsByName['workout_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get date =>
      columnsByName['date']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get completedRideId =>
      columnsByName['completed_ride_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_54(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'date',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<String> _column_55(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'completed_ride_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'REFERENCES rides (id)',
      ),
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get rideId =>
      columnsByName['ride_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get durationSeconds =>
      columnsByName['duration_seconds']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get watts =>
      columnsByName['watts']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get achievedAt =>
      columnsByName['achieved_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<double> _column_56(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'watts',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<int> _column_57(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'achieved_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get effectiveDate =>
      columnsByName['effective_date']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get ftp =>
      columnsByName['ftp']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<int> _column_58(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'effective_date',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );

final class Schema5 extends i0.VersionedSchema {
  Schema5({required super.database}) : super(version: 5);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    rides,
    sensorReadings,
    laps,
    workouts,
    workoutSteps,
    userProfiles,
    exportQueue,
    scheduledWorkouts,
    personalRecords,
    ftpHistory,
  ];
  late final Shape10 rides = Shape10(
    source: i0.VersionedTable(
      entityName: 'rides',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_59,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 sensorReadings = Shape1(
    source: i0.VersionedTable(
      entityName: 'sensor_readings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 laps = Shape2(
    source: i0.VersionedTable(
      entityName: 'laps',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_19,
        _column_20,
        _column_28,
        _column_29,
        _column_1,
        _column_30,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 workouts = Shape3(
    source: i0.VersionedTable(
      entityName: 'workouts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_31, _column_32, _column_33],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 workoutSteps = Shape4(
    source: i0.VersionedTable(
      entityName: 'workout_steps',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_19,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 userProfiles = Shape5(
    source: i0.VersionedTable(
      entityName: 'user_profiles',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_31,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 exportQueue = Shape11(
    source: i0.VersionedTable(
      entityName: 'export_queue',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_19,
        _column_20,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_52,
        _column_53,
        _column_60,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 scheduledWorkouts = Shape7(
    source: i0.VersionedTable(
      entityName: 'scheduled_workouts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_34,
        _column_54,
        _column_55,
        _column_4,
        _column_53,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 personalRecords = Shape8(
    source: i0.VersionedTable(
      entityName: 'personal_records',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(ride_id, duration_seconds)'],
      columns: [_column_19, _column_20, _column_37, _column_56, _column_57],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 ftpHistory = Shape9(
    source: i0.VersionedTable(
      entityName: 'ftp_history',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_19, _column_58, _column_43],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get startTime =>
      columnsByName['start_time']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get endTime =>
      columnsByName['end_time']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get workoutId =>
      columnsByName['workout_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get avgPower =>
      columnsByName['avg_power']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get normalizedPower =>
      columnsByName['normalized_power']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get maxPower =>
      columnsByName['max_power']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get avgCadence =>
      columnsByName['avg_cadence']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get avgHr =>
      columnsByName['avg_hr']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get maxHr =>
      columnsByName['max_hr']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get totalDistance =>
      columnsByName['total_distance']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get durationSeconds =>
      columnsByName['duration_seconds']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get pauseDurationSeconds =>
      columnsByName['pause_duration_seconds']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get tss =>
      columnsByName['tss']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get intensityFactor =>
      columnsByName['intensity_factor']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get ftpAtTime =>
      columnsByName['ftp_at_time']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get elevationGainM =>
      columnsByName['elevation_gain_m']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<double> _column_59(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'elevation_gain_m',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get rideId =>
      columnsByName['ride_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get target =>
      columnsByName['target']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get retryCount =>
      columnsByName['retry_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastAttempt =>
      columnsByName['last_attempt']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get errorMessage =>
      columnsByName['error_message']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get resultPath =>
      columnsByName['result_path']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_60(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'result_path',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      case 4:
        final schema = Schema5(database: database);
        final migrator = i1.Migrator(database, schema);
        await from4To5(migrator, schema);
        return 5;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(
    from2To3: from2To3,
    from3To4: from3To4,
    from4To5: from4To5,
  ),
);
